#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Install Timy.ai as a systemd service. Run inside the container that will
# serve it (the gateway node, pve-1, is the natural home).
#
#   sudo ./install.sh --upstream http://10.0.0.201:4000 --api-key sk-...
#
# Uses a venv rather than system pip so a distro upgrade cannot break it.
# ---------------------------------------------------------------------------
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UPSTREAM="http://127.0.0.1:4000"
API_KEY=""
PORT=8090
BIND="0.0.0.0"
SERVICE_USER="timy"

die() { echo "error: $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --upstream) UPSTREAM="$2"; shift 2 ;;
    --api-key)  API_KEY="$2"; shift 2 ;;
    --port)     PORT="$2"; shift 2 ;;
    --bind)     BIND="$2"; shift 2 ;;
    --user)     SERVICE_USER="$2"; shift 2 ;;
    -h|--help)  sed -n '2,9p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "must run as root (needs to write a systemd unit)"
command -v python3 >/dev/null || die "python3 not found"

echo "==> installing OS packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends python3-venv python3-pip curl

echo "==> creating venv at ${HERE}/.venv"
python3 -m venv "${HERE}/.venv"
"${HERE}/.venv/bin/pip" install --quiet --upgrade pip
"${HERE}/.venv/bin/pip" install --quiet -r "${HERE}/requirements.txt"

# Unprivileged service account. Timy needs no privilege: it reads persona.md
# and knowledge/, writes data/, and makes outbound HTTP calls.
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  echo "==> creating service user ${SERVICE_USER}"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

mkdir -p "${HERE}/data" "${HERE}/knowledge"
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${HERE}/data"
# knowledge/ and persona.md stay owned by you and readable by the service --
# you edit them, Timy only reads them.
chmod -R a+rX "${HERE}/knowledge" "${HERE}/persona.md" "${HERE}/ui" "${HERE}/api"

# Secrets go in an env file with restrictive permissions, not in the unit,
# because unit files are world-readable.
ENVFILE="/etc/timy.env"
cat > "$ENVFILE" <<ENV
UPSTREAM_BASE_URL=${UPSTREAM}
UPSTREAM_API_KEY=${API_KEY}
TIMY_HOST=${BIND}
TIMY_PORT=${PORT}
ENV
chmod 0640 "$ENVFILE"
chown root:"$SERVICE_USER" "$ENVFILE"
echo "==> wrote ${ENVFILE} (mode 0640)"

cat > /etc/systemd/system/timy.service <<UNIT
# Generated by timy/install.sh -- re-run the script rather than editing.
[Unit]
Description=Timy.ai
Documentation=file://${HERE}/README.md
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${HERE}
EnvironmentFile=${ENVFILE}
ExecStart=${HERE}/.venv/bin/python -m uvicorn api.main:app --host ${BIND} --port ${PORT}
Restart=always
RestartSec=5
# Embedding the knowledge base on first start can take minutes on CPU.
TimeoutStartSec=900

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=${HERE}/data

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable timy.service >/dev/null
systemctl restart timy.service

echo "==> waiting for Timy to answer"
ok=0
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${PORT}/api/health" >/dev/null 2>&1; then ok=1; break; fi
  sleep 2
done

if [[ $ok -eq 1 ]]; then
  echo
  echo "==> Timy is up: http://$(hostname -I | awk '{print $1}'):${PORT}"
  curl -fsS "http://127.0.0.1:${PORT}/api/health" | python3 -m json.tool 2>/dev/null || true
  echo
  echo "If 'upstream.reachable' is false, Timy is running but cannot see the"
  echo "gateway. Check --upstream and that the gateway is actually up."
else
  echo "==> Timy did not come up. Logs:" >&2
  journalctl -u timy -n 40 --no-pager >&2
  exit 1
fi
